import { describe, expect, it, vi } from "vitest";
import { ApiError } from "@lynse/core/api/client";
import {
  createInfographicSummaryHtml,
  mergePendingSummaryTab,
  parseFileTags,
  replaceSummaryTemplate,
  rerunSummaryPipeline,
  sortConclusionsChronologically,
  waitForAiTaskResult,
  waitForConclusionCompletion,
  waitForTranscriptionCompletion,
  addSummaryPipeline,
  isTranscriptionCompleted,
} from "./use-files";

describe("summary task polling", () => {
  it("orders newly created summary tabs after older summaries", () => {
    const summaries = sortConclusionsChronologically([
      {
        id: "new",
        fileId: "file_1",
        conclusionText: "new summary",
        createdAt: "",
        createTime: "2026-07-14 00:10:28",
      },
      {
        id: "old",
        fileId: "file_1",
        conclusionText: "old summary",
        createdAt: "",
        createTime: "2026-07-14 00:08:16",
      },
    ]);

    expect(summaries.map((summary) => summary.id)).toEqual(["old", "new"]);
  });

  it("polls transcription status until the file reaches a terminal state", async () => {
    const getStatus = vi
      .fn()
      .mockResolvedValueOnce({ file_1: "processing" })
      .mockResolvedValueOnce({ file_1: "COMPLETED" });

    const result = await waitForTranscriptionCompletion({
      fileIds: ["file_1"],
      getStatus,
      sleep: async () => {},
    });

    expect(result.file_1).toBe("COMPLETED");
    expect(getStatus).toHaveBeenCalledTimes(2);
  });

  it("polls an AI conclusion task until the generated conclusion is available", async () => {
    const getResult = vi
      .fn()
      .mockRejectedValueOnce(new ApiError(1001, "TASK_PROCESSING"))
      .mockResolvedValueOnce({
        status: "ASK_PROCESSING",
        taskId: "task_1",
        conclusion: {
          id: null,
          fileId: "file_1",
          conclusionText: null,
          generateSuccess: false,
          status: "RUNNING",
        },
      })
      .mockResolvedValueOnce({
        status: "COMPLETED",
        taskId: "task_1",
        conclusion: {
          id: "conclusion_1",
          fileId: "file_1",
          conclusionText: "done",
          generateSuccess: true,
        },
      });

    const result = await waitForAiTaskResult({
      fileId: "file_1",
      taskId: "task_1",
      aiTaskType: "CONCLUSION",
      getResult,
      sleep: async () => {},
    });

    expect(result.conclusion?.conclusionText).toBe("done");
    expect(getResult).toHaveBeenCalledWith({
      fileId: "file_1",
      taskId: "task_1",
      aiTaskType: "CONCLUSION",
    });
    expect(getResult).toHaveBeenCalledTimes(3);
  });

  it("polls the conclusion generated by a processing task", async () => {
    const previousConclusion = {
      id: "conclusion_1",
      fileId: "file_1",
      conclusionText: "old summary",
      createdAt: "before",
      updateTime: "before",
      generateSuccess: true,
    };
    const getConclusions = vi
      .fn()
      .mockRejectedValueOnce(new ApiError(1001, "TASK_PROCESSING"))
      .mockResolvedValueOnce([
        {
          ...previousConclusion,
          conclusionText: null as unknown as string,
          updateTime: "processing",
          status: "PROCESSING",
          generateSuccess: false,
        },
      ])
      .mockResolvedValueOnce([
        {
          ...previousConclusion,
          conclusionText: "new summary",
          updateTime: "after",
        },
      ]);

    const result = await waitForConclusionCompletion({
      fileId: "file_1",
      previousConclusions: [previousConclusion],
      getConclusions,
      sleep: async () => {},
    });

    expect(result.conclusionText).toBe("new summary");
    expect(getConclusions).toHaveBeenCalledWith({ fileId: "file_1" });
    expect(getConclusions).toHaveBeenCalledTimes(3);
  });

  it("treats error.first.conclusion.not.ready (code 500) as a transient 'keep polling' state", async () => {
    const previousConclusion = {
      id: "conclusion_1",
      fileId: "file_1",
      conclusionText: "old summary",
      createdAt: "before",
      updateTime: "before",
      generateSuccess: true,
    };
    const getConclusions = vi
      .fn()
      .mockRejectedValueOnce(new ApiError(500, "error.first.conclusion.not.ready"))
      .mockResolvedValueOnce([
        {
          ...previousConclusion,
          conclusionText: "new summary",
          updateTime: "after",
        },
      ]);

    const result = await waitForConclusionCompletion({
      fileId: "file_1",
      previousConclusions: [previousConclusion],
      getConclusions,
      sleep: async () => {},
    });

    expect(result.conclusionText).toBe("new summary");
    expect(getConclusions).toHaveBeenCalledTimes(2);
  });

  it("waits for the summary created by POST /file/trans", async () => {
    const previousConclusion = {
      id: "old_conclusion",
      fileId: "file_1",
      conclusionText: "old summary",
      createdAt: "before",
    };
    const getCurrentConclusions = vi.fn().mockResolvedValue([previousConclusion]);
    const startProcessing = vi.fn().mockResolvedValue({ taskId: "processing_task" });
    const waitForProcessing = vi.fn().mockResolvedValue({ file_1: "SUCCESS" });
    const waitForConclusion = vi.fn().mockResolvedValue({
      id: "conclusion_1",
      fileId: "file_1",
      conclusionText: "new summary",
      createdAt: "now",
      generateSuccess: true,
    });

    const result = await rerunSummaryPipeline({
      req: { fileId: "file_1", templateId: "template_1" },
      getCurrentConclusions,
      startProcessing,
      waitForProcessing,
      waitForConclusion,
    });

    expect(startProcessing).toHaveBeenCalledWith({
      fileId: "file_1",
      templateId: "template_1",
    });
    expect(waitForConclusion).toHaveBeenCalledWith({
      fileId: "file_1",
      previousConclusions: [previousConclusion],
      intervalMs: 5000,
      maxAttempts: 240,
    });
    expect(result.conclusion?.conclusionText).toBe("new summary");
    expect(getCurrentConclusions.mock.invocationCallOrder[0]).toBeLessThan(
      startProcessing.mock.invocationCallOrder[0]!,
    );
    expect(startProcessing.mock.invocationCallOrder[0]).toBeLessThan(
      waitForProcessing.mock.invocationCallOrder[0]!,
    );
    expect(waitForProcessing.mock.invocationCallOrder[0]).toBeLessThan(
      waitForConclusion.mock.invocationCallOrder[0]!,
    );
  });

  it("retries add-summary task creation on error.first.conclusion.not.ready, then waits for the result", async () => {
    const startAiTask = vi
      .fn()
      .mockRejectedValueOnce(new ApiError(500, "error.first.conclusion.not.ready"))
      .mockResolvedValueOnce("task_1");
    const waitForResult = vi.fn().mockResolvedValue({
      status: "COMPLETED",
      taskId: "task_1",
      conclusion: {
        id: "conclusion_1",
        fileId: "file_1",
        conclusionText: "add summary",
        generateSuccess: true,
      },
    });

    const result = await addSummaryPipeline({
      req: { fileId: "file_1", templateId: "template_1", aiTaskType: "CONCLUSION" },
      startAiTask,
      waitForResult,
      sleep: async () => {},
    });

    expect(startAiTask).toHaveBeenCalledTimes(2);
    expect(result.conclusion?.conclusionText).toBe("add summary");
    expect(waitForResult).toHaveBeenCalledWith({
      fileId: "file_1",
      taskId: "task_1",
      aiTaskType: "CONCLUSION",
    });
  });

  it("falls back to the initial transcription pipeline when the add task never becomes ready", async () => {
    // File has no first conclusion yet: every attempt to create the add task
    // fails with `not.ready`. The pipeline must fall back to rerun (initial
    // transcription + first summary) instead of surfacing "添加总结失败".
    const startAiTask = vi
      .fn()
      .mockRejectedValue(new ApiError(500, "error.first.conclusion.not.ready"));
    const startRerun = vi.fn().mockResolvedValue({
      status: "COMPLETED",
      taskId: "rerun_task_1",
      conclusion: {
        id: "conclusion_1",
        fileId: "file_1",
        conclusionText: "first summary",
        generateSuccess: true,
      },
    });
    const waitForResult = vi.fn();

    const result = await addSummaryPipeline({
      req: { fileId: "file_1", templateId: "template_1", aiTaskType: "CONCLUSION" },
      startAiTask,
      startRerun,
      waitForResult,
      sleep: async () => {},
      intervalMs: 0,
      maxAttempts: 3,
    });

    // Retried up to maxAttempts, then gave up on add and fell back to rerun.
    expect(startAiTask).toHaveBeenCalledTimes(3);
    expect(startRerun).toHaveBeenCalledTimes(1);
    expect(startRerun).toHaveBeenCalledWith({
      fileId: "file_1",
      templateId: "template_1",
      modelId: undefined,
      languageId: undefined,
    });
    // The add-result waiter is never reached once we fall back.
    expect(waitForResult).not.toHaveBeenCalled();
    expect(result.conclusion?.conclusionText).toBe("first summary");
  });

  it("replaces a summary by generating the new one before deleting the old one", async () => {
    const startAiTask = vi.fn().mockResolvedValue("task_1");
    const waitForResult = vi.fn().mockResolvedValue({
      status: "COMPLETED",
      taskId: "task_1",
      conclusion: {
        id: "new_conclusion",
        fileId: "file_1",
        conclusionText: "new summary",
        generateSuccess: true,
      },
    });
    const deleteConclusion = vi.fn().mockResolvedValue(undefined);

    const result = await replaceSummaryTemplate({
      fileId: "file_1",
      oldConclusionId: "old_conclusion",
      templateId: "template_1",
      startAiTask,
      waitForResult,
      deleteConclusion,
    });

    expect(result.conclusion?.id).toBe("new_conclusion");
    expect(startAiTask).toHaveBeenCalledWith({
      aiTaskType: "CONCLUSION",
      fileId: "file_1",
      templateId: "template_1",
    });
    expect(deleteConclusion).toHaveBeenCalledWith("old_conclusion");
    const waitCallOrder = waitForResult.mock.invocationCallOrder[0];
    const deleteCallOrder = deleteConclusion.mock.invocationCallOrder[0];
    expect(waitCallOrder).toBeDefined();
    expect(deleteCallOrder).toBeDefined();
    expect(waitCallOrder!).toBeLessThan(deleteCallOrder!);
  });

  it("replaces a pending summary tab with the generated conclusion", () => {
    const tabs = mergePendingSummaryTab({
      tabs: [
        { key: "existing-0", id: "old", name: "旧总结", text: "old", status: "ready" },
        { key: "pending-1", id: "", name: "项目汇报", text: "", status: "pending", pendingId: "pending-1" },
      ],
      pendingId: "pending-1",
      conclusion: {
        id: "new",
        fileId: "file_1",
        conclusionText: "new content",
        templateName: "项目汇报",
        createdAt: "now",
      },
    });

    expect(tabs).toEqual([
      { key: "existing-0", id: "old", name: "旧总结", text: "old", status: "ready" },
      { key: "new", id: "new", name: "项目汇报", text: "new content", status: "ready" },
    ]);
  });

  it("parses tags from common file list fields", () => {
    expect(parseFileTags({ tags: "销售, 复盘 项目" })).toEqual(["销售", "复盘", "项目"]);
    expect(parseFileTags({ tagList: ["会议", "客户"] })).toEqual(["会议", "客户"]);
    expect(parseFileTags({ categoryName: "访谈" })).toEqual(["访谈"]);
    expect(parseFileTags({ folderName: "项目会议" })).toEqual(["项目会议"]);
  });

  it("creates marked infographic summary html from generated text", () => {
    const html = createInfographicSummaryHtml({
      title: "AI硬件与数字版权创新",
      source: "核心结论\n- 产品方向：覆盖动态展示场景\n- 技术实现：AI生成内容\n- 商业模式：版权运营",
    });

    expect(html).toContain('data-summary-template="infographic"');
    expect(html).toContain("AI硬件与数字版权创新");
    expect(html).toContain("核心发展脉络");
    expect(html).toContain("产品方向");
    expect(html).toContain("技术实现");
  });
});

describe("isTranscriptionCompleted", () => {
  it("treats a completed status as already transcribed", () => {
    expect(isTranscriptionCompleted("completed")).toBe(true);
    expect(isTranscriptionCompleted({ status: "success" })).toBe(true);
    expect(isTranscriptionCompleted("1")).toBe(true);
  });

  it("treats missing / in-progress / failed status as not transcribed", () => {
    expect(isTranscriptionCompleted(undefined)).toBe(false);
    expect(isTranscriptionCompleted("not_started")).toBe(false);
    expect(isTranscriptionCompleted({ status: "transcribing" })).toBe(false);
    expect(isTranscriptionCompleted("failed")).toBe(false);
  });
});
